#define _CRT_SECURE_NO_WARNINGS
#include <stdint.h>
#include <stdlib.h>
#include <memory.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#define SDL_MAIN_HANDLED
#include <SDL.h>
#include <Windows.h>
#include <GL/gl.h>
